pyms:
  services:
    requests:
      data: ""
    swagger:
        path: "swagger"
        file: "swagger.yaml"
        url: "/ui/"
        project_dir: "app.views"
    tracer:
        client: "jaeger"
        host: "localhost"
        component_name: "Codeground RCE"
    metrics: true
    service_discovery:
      service: "consul"
      host: "localhost"
      autoregister: true
    

  config:
    DEBUG: false
    TESTING: false
    APP_NAME: Codeground RCE
    APPLICATION_ROOT : /codeground-rce
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    SECRET_KEY: "gjr39dkjn344_!67#"
    DATABASE: db.sqlite3
    SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3
    CODEGROUND_CONFIG: "codeground-rce.conf"